export const STORE_FETCHED_CATEGORIES = 'STORE_FETCHED_CATEGORIES'
export const CATEGORIES_LOADED = 'CATEGORIES_LOADED'

export const STORE_FETCHED_CUSTOM_LOGO = 'STORE_FETCHED_CUSTOM_LOGO'
export const CUSTOM_LOGO_LOADED = 'CUSTOM_LOGO_LOADED'

export const STORE_FETCHED_MENUS = 'STORE_FETCHED_MENUS'
export const MENUS_LOADED = 'MENUS_LOADED'

export const STORE_FETCHED_PAGES = 'STORE_FETCHED_PAGES'
export const PAGES_LOADED = 'PAGES_LOADED'

/*
export const STORE_FETCHED_SOME_PAGES = 'STORE_FETCHED_SOME_PAGES'
export const SOME_PAGES_LOADED = 'SOME_PAGES_LOADED'
*/

export const STORE_FETCHED_PAGE_COUNT = 'STORE_FETCHED_PAGE_COUNT'
export const PAGE_COUNT_LOADED = 'PAGE_COUNT_LOADED'

export const STORE_FETCHED_POSTS = 'STORE_FETCHED_POSTS'
export const POSTS_LOADED = 'POSTS_LOADED'

export const STORE_FETCHED_POST_COUNT = 'STORE_FETCHED_POST_COUNT'
export const POST_COUNT_LOADED = 'POST_COUNT_LOADED'

export const STORE_FETCHED_CATEGORY_POSTS = 'STORE_FETCHED_CATEGORY_POSTS'
export const CATEGORY_POSTS_LOADED = 'CATEGORY_POSTS_LOADED'

export const STORE_FETCHED_TAG_POSTS = 'STORE_FETCHED_TAG_POSTS'
export const TAG_POSTS_LOADED = 'TAG_POSTS_LOADED'

export const STORE_FETCHED_USER = 'STORE_FETCHED_USER'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'

export const INCREMENT_LOADING_PROGRESS = 'INCREMENT_LOADING_PROGRESS'
export const RESET_LOADING_PROGRESS = 'RESET_LOADING_PROGRESS'
